-- Please check LICENSE file for license related details
-- Author: Rohan Vashisht


-- mod-version:3
local syntax = require "core.syntax"

syntax.add {
    name = "Carbon",
    files = { "%.carbon$" },
    comment = "//",
    patterns = {
        { pattern = { '"', '"', '\\' },       type = "string" },
        { pattern = { '"""', '"""'; '\\' },  type = "string"   },
        { pattern = "//.*",                    type = "comment" },
        { pattern = "[!%-/*?:=><+]",             type = "operator" },
        { pattern = "[%a_][%w_]*%f[(]",       type = "function" },
        { pattern = "package%s+()[%a_][%w_]*",  type = { "keyword", "literal" } },
        { pattern = "let%s+()[%a_][%w_]*",  type = { "keyword", "literal" } },
        { pattern = "import%s+()[%a_][%w_]*",  type = { "keyword", "literal" } },
        { pattern = "impl%s+()[%a_][%w_]*", type = { "keyword", "literal" } },
        { pattern = "class%s+()[%a_][%w_]*", type = { "keyword", "literal" } },
        { pattern = "var%s+()[%a_][%w_]*",    type = { "keyword", "literal" } },
        { pattern = "-?%d+[%d%.eE_]*",        type = "number" },
        { pattern = "-?%.?%d+",               type = "number" },
        { pattern = "[%a_][%w_]*",               type = "normal" },
    },
    symbols = {
        ["package"] = "keyword",
        ["import"] = "keyword",
        ["fn"] = "keyword",
        ["var"] = "keyword",
        ["for"] = "keyword",
        ["return"] = "keyword",
        ["class"] = "keyword",
        ["api"] = "keyword",
        ["i8"] = "keyword",
        ["i16"] = "keyword",
        ["i32"] = "keyword",
        ["i64"] = "keyword",
        ["i128"] = "keyword",
        ["i256"] = "keyword",
        ["u8"] = "keyword",
        ["u16"] = "keyword",
        ["u32"] = "keyword",
        ["u64"] = "keyword",
        ["u128"] = "keyword",
        ["u256"] = "keyword",
        ["f8"] = "keyword",
        ["f16"] = "keyword",
        ["f32"] = "keyword",
        ["f64"] = "keyword",
        ["f128"] = "keyword",
        ["f256"] = "keyword",
        ["if"] = "keyword",
        ["else"] = "keyword",
        ["auto"] = "keyword",
        ["let"] = "keyword",
        ["File"] = "keyword",
        ["while"] = "keyword",
        ["for"] = "keyword",
        ["match"] = "keyword",
        ["case"] = "keyword",
        ["default"] = "keyword",
        ["returned"] = "keyword",
        ["base"] = "keyword",
        ["virtual"] = "keyword",
        ["abstract"] = "keyword",
        ["impl"] = "keyword2",
        ["extend"] = "keyword",
        ["partial"] = "keyword2",
        ["Self"] = "keyword",
        ["Int"] = "keyword",
        ["UInt"] = "keyword",
        ["Base"] = "keyword",
        ["template"] = "keyword2",
    }
}
